export const COUNTRIES = [
  "Afghanistan", "Aland Islands", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic",
  "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
  "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
  "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman",
  "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar",
  "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan",
  "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
  "Yemen",
  "Zambia", "Zimbabwe"
];

export const INDIAN_STATES = [
  "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar",
  "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa",
  "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka",
  "Kerala", "Ladakh", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan",
  "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const USA_STATES = [
  "Alabama", "Alaska", "American Samoa", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
  "Delaware", "District of Columbia", "Florida", "Georgia", "Guam", "Hawaii", "Idaho", "Illinois", 
  "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
  "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", 
  "New Mexico", "New York", "North Carolina", "North Dakota", "Northern Mariana Islands", "Ohio", "Oklahoma", 
  "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
  "Texas", "U.S. Virgin Islands", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
];

export const UK_STATES = [
  "England", "Scotland", "Wales", "Northern Ireland",
  // Ceremonial counties of England for more options
  "Bedfordshire", "Berkshire", "Bristol", "Buckinghamshire", "Cambridgeshire", "Cheshire", "Cornwall", "Cumbria", "Derbyshire", "Devon", "Dorset", "Durham", "East Riding of Yorkshire", "East Sussex", "Essex", "Gloucestershire", "Greater London", "Greater Manchester", "Hampshire", "Herefordshire", "Hertfordshire", "Isle of Wight", "Kent", "Lancashire", "Leicestershire", "Lincolnshire", "Merseyside", "Norfolk", "North Yorkshire", "Northamptonshire", "Northumberland", "Nottinghamshire", "Oxfordshire", "Rutland", "Shropshire", "Somerset", "South Yorkshire", "Staffordshire", "Suffolk", "Surrey", "Tyne and Wear", "Warwickshire", "West Midlands", "West Sussex", "West Yorkshire", "Wiltshire", "Worcestershire"
];

export const ANDHRA_PRADESH_CITIES = [
  "Adoni", "Amaravati", "Anakapalle", "Anantapur", "Bapatla", "Bhimavaram", "Chirala", "Chittoor", 
  "Dharmavaram", "Eluru", "Gooty", "Gudivada", "Guntur", "Hindupur", "Kadapa", "Kakinada", "Kavali", 
  "Kurnool", "Machilipatnam", "Madanapalle", "Mangalagiri", "Markapur", "Nandyal", "Narasaraopet", 
  "Nellore", "Ongole", "Palakollu", "Proddatur", "Rajahmundry", "Rayachoti", "Srikakulam", "Tadipatri", 
  "Tadepalligudem", "Tenali", "Tirupati", "Vijayawada", "Visakhapatnam", "Vizianagaram"
];

export const COUNTRY_CODES = [
  { name: 'India', code: '+91', iso: 'IN' },
  { name: 'United States of America', code: '+1', iso: 'US' },
  { name: 'United Kingdom', code: '+44', iso: 'GB' },
  { name: 'Australia', code: '+61', iso: 'AU' },
  { name: 'Afghanistan', code: '+93', iso: 'AF' },
  { name: 'Aland Islands', code: '+358', iso: 'AX' },
  { name: 'Albania', code: '+355', iso: 'AL' },
  { name: 'Algeria', code: '+213', iso: 'DZ' },
  { name: 'American Samoa', code: '+1684', iso: 'AS' },
  { name: 'Andorra', code: '+376', iso: 'AD' },
  { name: 'Angola', code: '+244', iso: 'AO' },
  { name: 'Anguilla', code: '+1264', iso: 'AI' },
  { name: 'Antigua and Barbuda', code: '+1268', iso: 'AG' },
  { name: 'Argentina', code: '+54', iso: 'AR' },
  { name: 'Armenia', code: '+374', iso: 'AM' },
  { name: 'Aruba', code: '+297', iso: 'AW' },
  { name: 'Austria', code: '+43', iso: 'AT' },
  { name: 'Azerbaijan', code: '+994', iso: 'AZ' },
  { name: 'Bahamas', code: '+1242', iso: 'BS' },
  { name: 'Bahrain', code: '+973', iso: 'BH' },
  { name: 'Bangladesh', code: '+880', iso: 'BD' },
  { name: 'Barbados', code: '+1246', iso: 'BB' },
  { name: 'Belarus', code: '+375', iso: 'BY' },
  { name: 'Belgium', code: '+32', iso: 'BE' },
  { name: 'Belize', code: '+501', iso: 'BZ' },
  { name: 'Benin', code: '+229', iso: 'BJ' },
  { name: 'Bermuda', code: '+1441', iso: 'BM' },
  { name: 'Bhutan', code: '+975', iso: 'BT' },
  { name: 'Bolivia', code: '+591', iso: 'BO' },
  { name: 'Bosnia and Herzegovina', code: '+387', iso: 'BA' },
  { name: 'Botswana', code: '+267', iso: 'BW' },
  { name: 'Brazil', code: '+55', iso: 'BR' },
  { name: 'Brunei', code: '+673', iso: 'BN' },
  { name: 'Bulgaria', code: '+359', iso: 'BG' },
  { name: 'Burkina Faso', code: '+226', iso: 'BF' },
  { name: 'Burundi', code: '+257', iso: 'BI' },
  { name: 'Cambodia', code: '+855', iso: 'KH' },
  { name: 'Cameroon', code: '+237', iso: 'CM' },
  { name: 'Canada', code: '+1', iso: 'CA' },
  { name: 'Cape Verde', code: '+238', iso: 'CV' },
  { name: 'Cayman Islands', code: '+1345', iso: 'KY' },
  { name: 'Central African Republic', code: '+236', iso: 'CF' },
  { name: 'Chad', code: '+235', iso: 'TD' },
  { name: 'Chile', code: '+56', iso: 'CL' },
  { name: 'China', code: '+86', iso: 'CN' },
  { name: 'Colombia', code: '+57', iso: 'CO' },
  { name: 'Comoros', code: '+269', iso: 'KM' },
  { name: 'Congo', code: '+242', iso: 'CG' },
  { name: 'Cook Islands', code: '+682', iso: 'CK' },
  { name: 'Costa Rica', code: '+506', iso: 'CR' },
  { name: 'Croatia', code: '+385', iso: 'HR' },
  { name: 'Cuba', code: '+53', iso: 'CU' },
  { name: 'Cyprus', code: '+357', iso: 'CY' },
  { name: 'Czech Republic', code: '+420', iso: 'CZ' },
  { name: 'Denmark', code: '+45', iso: 'DK' },
  { name: 'Djibouti', code: '+253', iso: 'DJ' },
  { name: 'Dominica', code: '+1767', iso: 'DM' },
  { name: 'Dominican Republic', code: '+1809', iso: 'DO' },
  { name: 'Ecuador', code: '+593', iso: 'EC' },
  { name: 'Egypt', code: '+20', iso: 'EG' },
  { name: 'El Salvador', code: '+503', iso: 'SV' },
  { name: 'Equatorial Guinea', code: '+240', iso: 'GQ' },
  { name: 'Eritrea', code: '+291', iso: 'ER' },
  { name: 'Estonia', code: '+372', iso: 'EE' },
  { name: 'Ethiopia', code: '+251', iso: 'ET' },
  { name: 'Faroe Islands', code: '+298', iso: 'FO' },
  { name: 'Fiji', code: '+679', iso: 'FJ' },
  { name: 'Finland', code: '+358', iso: 'FI' },
  { name: 'France', code: '+33', iso: 'FR' },
  { name: 'Gabon', code: '+241', iso: 'GA' },
  { name: 'Gambia', code: '+220', iso: 'GM' },
  { name: 'Georgia', code: '+995', iso: 'GE' },
  { name: 'Germany', code: '+49', iso: 'DE' },
  { name: 'Ghana', code: '+233', iso: 'GH' },
  { name: 'Greece', code: '+30', iso: 'GR' },
  { name: 'Greenland', code: '+299', iso: 'GL' },
  { name: 'Grenada', code: '+1473', iso: 'GD' },
  { name: 'Guatemala', code: '+502', iso: 'GT' },
  { name: 'Guinea', code: '+224', iso: 'GN' },
  { name: 'Guinea-Bissau', code: '+245', iso: 'GW' },
  { name: 'Guyana', code: '+509', iso: 'GY' },
  { name: 'Haiti', code: '+509', iso: 'HT' },
  { name: 'Honduras', code: '+504', iso: 'HN' },
  { name: 'Hong Kong', code: '+852', iso: 'HK' },
  { name: 'Hungary', code: '+36', iso: 'HU' },
  { name: 'Iceland', code: '+354', iso: 'IS' },
  { name: 'Indonesia', code: '+62', iso: 'ID' },
  { name: 'Iran', code: '+98', iso: 'IR' },
  { name: 'Iraq', code: '+964', iso: 'IQ' },
  { name: 'Ireland', code: '+353', iso: 'IE' },
  { name: 'Israel', code: '+972', iso: 'IL' },
  { name: 'Italy', code: '+39', iso: 'IT' },
  { name: 'Jamaica', code: '+1876', iso: 'JM' },
  { name: 'Japan', code: '+81', iso: 'JP' },
  { name: 'Jordan', code: '+962', iso: 'JO' },
  { name: 'Kazakhstan', code: '+7', iso: 'KZ' },
  { name: 'Kenya', code: '+254', iso: 'KE' },
  { name: 'Kiribati', code: '+686', iso: 'KI' },
  { name: 'Kuwait', code: '+965', iso: 'KW' },
  { name: 'Kyrgyzstan', code: '+996', iso: 'KG' },
  { name: 'Laos', code: '+856', iso: 'LA' },
  { name: 'Latvia', code: '+371', iso: 'LV' },
  { name: 'Lebanon', code: '+961', iso: 'LB' },
  { name: 'Lesotho', code: '+266', iso: 'LS' },
  { name: 'Liberia', code: '+231', iso: 'LR' },
  { name: 'Libya', code: '+218', iso: 'LY' },
  { name: 'Liechtenstein', code: '+423', iso: 'LI' },
  { name: 'Lithuania', code: '+370', iso: 'LT' },
  { name: 'Luxembourg', code: '+352', iso: 'LU' },
  { name: 'Macau', code: '+853', iso: 'MO' },
  { name: 'Madagascar', code: '+261', iso: 'MG' },
  { name: 'Malawi', code: '+265', iso: 'MW' },
  { name: 'Malaysia', code: '+60', iso: 'MY' },
  { name: 'Maldives', code: '+960', iso: 'MV' },
  { name: 'Mali', code: '+223', iso: 'ML' },
  { name: 'Malta', code: '+356', iso: 'MT' },
  { name: 'Mauritania', code: '+222', iso: 'MR' },
  { name: 'Mauritius', code: '+230', iso: 'MU' },
  { name: 'Mexico', code: '+52', iso: 'MX' },
  { name: 'Moldova', code: '+373', iso: 'MD' },
  { name: 'Monaco', code: '+377', iso: 'MC' },
  { name: 'Mongolia', code: '+976', iso: 'MN' },
  { name: 'Montenegro', code: '+382', iso: 'ME' },
  { name: 'Morocco', code: '+212', iso: 'MA' },
  { name: 'Mozambique', code: '+258', iso: 'MZ' },
  { name: 'Myanmar', code: '+95', iso: 'MM' },
  { name: 'Namibia', code: '+264', iso: 'NA' },
  { name: 'Nepal', code: '+977', iso: 'NP' },
  { name: 'Netherlands', code: '+31', iso: 'NL' },
  { name: 'New Zealand', code: '+64', iso: 'NZ' },
  { name: 'Nicaragua', code: '+505', iso: 'NI' },
  { name: 'Niger', code: '+227', iso: 'NE' },
  { name: 'Nigeria', code: '+234', iso: 'NG' },
  { name: 'North Korea', code: '+850', iso: 'KP' },
  { name: 'Norway', code: '+47', iso: 'NO' },
  { name: 'Oman', code: '+968', iso: 'OM' },
  { name: 'Pakistan', code: '+92', iso: 'PK' },
  { name: 'Palau', code: '+680', iso: 'PW' },
  { name: 'Panama', code: '+507', iso: 'PA' },
  { name: 'Papua New Guinea', code: '+675', iso: 'PG' },
  { name: 'Paraguay', code: '+595', iso: 'PY' },
  { name: 'Peru', code: '+51', iso: 'PE' },
  { name: 'Philippines', code: '+63', iso: 'PH' },
  { name: 'Poland', code: '+48', iso: 'PL' },
  { name: 'Portugal', code: '+351', iso: 'PT' },
  { name: 'Puerto Rico', code: '+1787', iso: 'PR' },
  { name: 'Qatar', code: '+974', iso: 'QA' },
  { name: 'Romania', code: '+40', iso: 'RO' },
  { name: 'Russia', code: '+7', iso: 'RU' },
  { name: 'Rwanda', code: '+250', iso: 'RW' },
  { name: 'Samoa', code: '+685', iso: 'WS' },
  { name: 'San Marino', code: '+378', iso: 'SM' },
  { name: 'Saudi Arabia', code: '+966', iso: 'SA' },
  { name: 'Senegal', code: '+221', iso: 'SN' },
  { name: 'Serbia', code: '+381', iso: 'RS' },
  { name: 'Seychelles', code: '+248', iso: 'SC' },
  { name: 'Sierra Leone', code: '+232', iso: 'SL' },
  { name: 'Singapore', code: '+65', iso: 'SG' },
  { name: 'Slovakia', code: '+421', iso: 'SK' },
  { name: 'Slovenia', code: '+386', iso: 'SI' },
  { name: 'Somalia', code: '+252', iso: 'SO' },
  { name: 'South Africa', code: '+27', iso: 'ZA' },
  { name: 'South Korea', code: '+82', iso: 'KR' },
  { name: 'Spain', code: '+34', iso: 'ES' },
  { name: 'Sri Lanka', code: '+94', iso: 'LK' },
  { name: 'Sudan', code: '+249', iso: 'SD' },
  { name: 'Suriname', code: '+597', iso: 'SR' },
  { name: 'Sweden', code: '+46', iso: 'SE' },
  { name: 'Switzerland', code: '+41', iso: 'CH' },
  { name: 'Syria', code: '+963', iso: 'SY' },
  { name: 'Taiwan', code: '+886', iso: 'TW' },
  { name: 'Tanzania', code: '+255', iso: 'TZ' },
  { name: 'Thailand', code: '+66', iso: 'TH' },
  { name: 'Togo', code: '+228', iso: 'TG' },
  { name: 'Tonga', code: '+676', iso: 'TO' },
  { name: 'Tunisia', code: '+216', iso: 'TN' },
  { name: 'Turkey', code: '+90', iso: 'TR' },
  { name: 'Turkmenistan', code: '+993', iso: 'TM' },
  { name: 'Uganda', code: '+256', iso: 'UG' },
  { name: 'Ukraine', code: '+380', iso: 'UA' },
  { name: 'United Arab Emirates', code: '+971', iso: 'AE' },
  { name: 'Uruguay', code: '+598', iso: 'UY' },
  { name: 'Uzbekistan', code: '+998', iso: 'UZ' },
  { name: 'Venezuela', code: '+58', iso: 'VE' },
  { name: 'Vietnam', code: '+84', iso: 'VN' },
  { name: 'Yemen', code: '+967', iso: 'YE' },
  { name: 'Zambia', code: '+260', iso: 'ZM' },
  { name: 'Zimbabwe', code: '+263', iso: 'ZW' },
];

export const PREVIEW_VIDEOS = [
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
];

export const ALL_NATIVE_LANGUAGES = [
    "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Assamese", "Azerbaijani", "Belarusian", "Bemba", "Bengali", "Bhojpuri", "Bislama", "Bodo", "Bosnian", "Bulgarian", "Burmese", "Catalan", "Cebuano", "Chichewa", "Chinese (Cantonese)", "Chinese (Mandarin)", "Chhattisgarhi", "Chittagonian", "Comorian", "Croatian", "Czech", "Danish", "Deccan", "Dhivehi", "Dogri", "Dutch", "Dzongkha", "English", "Estonian", "Farsi (Persian)", "Fijian", "Filipino (Tagalog)", "Finnish", "French", "Georgian", "German", "Gilbertese", "Greek", "Guarani", "Gujarati", "Haitian Creole", "Haryanvi", "Hausa", "Hebrew", "Hindi", "Hiri Motu", "Hungarian", "Icelandic", "Igbo", "Indonesian", "Irish", "Italian", "Japanese", "Javanese", "Kannada", "Kashmiri", "Kazakh", "Khmer", "Kinyarwanda", "Kirundi", "Konkani", "Korean", "Kurdish", "Kyrgyz", "Lao", "Latin", "Latvian", "Lithuanian", "Luxembourgish", "Macedonian", "Magahi", "Maithili", "Malagasy", "Malay", "Malayalam", "Maltese", "Manipuri", "Marathi", "Marshallese", "Mongolian", "Montenegrin", "Nauruan", "Ndebele", "Nepali", "Norwegian", "Nyanja", "Odia (Oriya)", "Palauan", "Papiamento", "Pashto", "Polish", "Portuguese", "Punjabi", "Rajasthani", "Romanian", "Russian", "Samoan", "Sango", "Sanskrit", "Santali", "Saraiki", "Serbian", "Sesotho", "Seychellois Creole", "Shona", "Sindhi", "Sinhala", "Slovak", "Slovene", "Somali", "Spanish", "Sundanese", "Swahili", "Swazi", "Swedish", "Sylheti", "Tajik", "Tamil", "Telugu", "Tetum", "Thai", "Tigrinya", "Tok Pisin", "Tongan", "Tswana", "Turkish", "Turkmen", "Tuvaluan", "Ukrainian", "Urdu", "Uzbek", "Vietnamese", "Yoruba", "Zulu"
];

export const COUNTRY_LANGUAGES: Record<string, string[]> = {
  'Afghanistan': ['English', 'Farsi (Persian)', 'Pashto'],
  'Aland Islands': ['English', 'Swedish'],
  'Albania': ['Albanian', 'English'],
  'Algeria': ['Arabic', 'English', 'French'],
  'Andorra': ['Catalan', 'English'],
  'Angola': ['English', 'Portuguese'],
  'Antigua and Barbuda': ['English'],
  'Argentina': ['English', 'Spanish'],
  'Armenia': ['Armenian', 'English'],
  'Aruba': ['Dutch', 'English', 'Papiamento'],
  'Australia': ['English'],
  'Austria': ['English', 'German'],
  'Azerbaijan': ['Azerbaijani', 'English'],
  'Bahamas': ['English'],
  'Bahrain': ['Arabic', 'English'],
  'Bangladesh': ['Bengali', 'English'],
  'Barbados': ['English'],
  'Belarus': ['Belarusian', 'English', 'Russian'],
  'Belgium': ['Dutch', 'English', 'French', 'German'],
  'Belize': ['English', 'Spanish'],
  'Benin': ['English', 'French'],
  'Bhutan': ['Dzongkha', 'English'],
  'Bolivia': ['English', 'Spanish'],
  'Bosnia and Herzegovina': ['Bosnian', 'Croatian', 'English', 'Serbian'],
  'Botswana': ['English', 'Tswana'],
  'Brazil': ['English', 'Portuguese'],
  'Brunei': ['English', 'Malay'],
  'Bulgaria': ['Bulgarian', 'English'],
  'Burkina Faso': ['English', 'French'],
  'Burundi': ['English', 'French', 'Kirundi'],
  'Cabo Verde': ['English', 'Portuguese'],
  'Cambodia': ['English', 'Khmer'],
  'Cameroon': ['English', 'French'],
  'Canada': ['English', 'French'],
  'Central African Republic': ['English', 'French', 'Sango'],
  'Chad': ['Arabic', 'English', 'French'],
  'Chile': ['English', 'Spanish'],
  'China': ['Chinese (Cantonese)', 'Chinese (Mandarin)', 'English'],
  'Colombia': ['English', 'Spanish'],
  'Comoros': ['Arabic', 'Comorian', 'English', 'French'],
  'Congo, Democratic Republic of the': ['English', 'French'],
  'Congo, Republic of the': ['English', 'French'],
  'Costa Rica': ['English', 'Spanish'],
  'Cote d\'Ivoire': ['English', 'French'],
  'Croatia': ['Croatian', 'English'],
  'Cuba': ['English', 'Spanish'],
  'Cyprus': ['English', 'Greek', 'Turkish'],
  'Czech Republic': ['Czech', 'English'],
  'Denmark': ['Danish', 'English'],
  'Djibouti': ['Arabic', 'English', 'French'],
  'Dominica': ['English'],
  'Dominican Republic': ['English', 'Spanish'],
  'Ecuador': ['English', 'Spanish'],
  'Egypt': ['Arabic', 'English'],
  'El Salvador': ['English', 'Spanish'],
  'Equatorial Guinea': ['English', 'French', 'Portuguese', 'Spanish'],
  'Eritrea': ['Arabic', 'English', 'Tigrinya'],
  'Estonia': ['English', 'Estonian'],
  'Eswatini': ['English', 'Swazi'],
  'Ethiopia': ['Amharic', 'English'],
  'Fiji': ['English', 'Fijian', 'Hindi'],
  'Finland': ['English', 'Finnish'],
  'France': ['English', 'French'],
  'Gabon': ['English', 'French'],
  'Gambia': ['English'],
  'Georgia': ['English', 'Georgian'],
  'Germany': ['English', 'German'],
  'Ghana': ['English'],
  'Greece': ['English', 'Greek'],
  'Grenada': ['English'],
  'Guatemala': ['English', 'Spanish'],
  'Guinea': ['English', 'French'],
  'Guinea-Bissau': ['English', 'Portuguese'],
  'Guyana': ['English'],
  'Haiti': ['English', 'French', 'Haitian Creole'],
  'Honduras': ['English', 'Spanish'],
  'Hungary': ['English', 'Hungarian'],
  'Iceland': ['English', 'Icelandic'],
  'India': ['Assamese', 'Bengali', 'Bodo', 'Dogri', 'English', 'Gujarati', 'Hindi', 'Kannada', 'Kashmiri', 'Konkani', 'Maithili', 'Malayalam', 'Manipuri', 'Marathi', 'Nepali', 'Odia (Oriya)', 'Punjabi', 'Sanskrit', 'Santali', 'Sindhi', 'Tamil', 'Telugu', 'Urdu'],
  'Indonesia': ['English', 'Indonesian'],
  'Iran': ['English', 'Farsi (Persian)'],
  'Iraq': ['Arabic', 'English', 'Kurdish'],
  'Ireland': ['English', 'Irish'],
  'Israel': ['English', 'Hebrew'],
  'Italy': ['English', 'Italian'],
  'Jamaica': ['English'],
  'Japan': ['English', 'Japanese'],
  'Jordan': ['Arabic', 'English'],
  'Kazakhstan': ['English', 'Kazakh', 'Russian'],
  'Kenya': ['English', 'Swahili'],
  'Kiribati': ['English', 'Gilbertese'],
  'Kosovo': ['Albanian', 'English', 'Serbian'],
  'Kuwait': ['Arabic', 'English'],
  'Kyrgyzstan': ['English', 'Kyrgyz', 'Russian'],
  'Laos': ['English', 'Lao'],
  'Latvia': ['English', 'Latvian'],
  'Lebanon': ['Arabic', 'English'],
  'Lesotho': ['English', 'Sesotho'],
  'Liberia': ['English'],
  'Libya': ['Arabic', 'English'],
  'Liechtenstein': ['English', 'German'],
  'Lithuania': ['English', 'Lithuanian'],
  'Luxembourg': ['English', 'French', 'German', 'Luxembourgish'],
  'Madagascar': ['English', 'French', 'Malagasy'],
  'Malawi': ['Chichewa', 'English'],
  'Malaysia': ['English', 'Malay'],
  'Maldives': ['Dhivehi', 'English'],
  'Mali': ['English', 'French'],
  'Malta': ['English', 'Maltese'],
  'Marshall Islands': ['English', 'Marshallese'],
  'Mauritania': ['Arabic', 'English'],
  'Mauritius': ['English', 'French'],
  'Mexico': ['English', 'Spanish'],
  'Micronesia': ['English'],
  'Moldova': ['English', 'Romanian'],
  'Monaco': ['English', 'French'],
  'Mongolia': ['English', 'Mongolian'],
  'Montenegro': ['English', 'Montenegrin'],
  'Morocco': ['Arabic', 'English', 'French'],
  'Mozambique': ['English', 'Portuguese'],
  'Myanmar': ['Burmese', 'English'],
  'Namibia': ['English'],
  'Nauru': ['English', 'Nauruan'],
  'Nepal': ['English', 'Nepali'],
  'Netherlands': ['Dutch', 'English'],
  'New Zealand': ['English'],
  'Nicaragua': ['English', 'Spanish'],
  'Niger': ['English', 'French'],
  'Nigeria': ['English', 'Hausa', 'Igbo', 'Yoruba'],
  'North Korea': ['English', 'Korean'],
  'North Macedonia': ['Albanian', 'English', 'Macedonian'],
  'Norway': ['English', 'Norwegian'],
  'Oman': ['Arabic', 'English'],
  'Pakistan': ['English', 'Pashto', 'Punjabi', 'Sindhi', 'Urdu'],
  'Palau': ['English', 'Palauan'],
  'Palestine': ['Arabic', 'English'],
  'Panama': ['English', 'Spanish'],
  'Papua New Guinea': ['English', 'Hiri Motu', 'Tok Pisin'],
  'Paraguay': ['English', 'Guarani', 'Spanish'],
  'Peru': ['English', 'Spanish'],
  'Philippines': ['English', 'Filipino (Tagalog)'],
  'Poland': ['English', 'Polish'],
  'Portugal': ['English', 'Portuguese'],
  'Qatar': ['Arabic', 'English'],
  'Romania': ['English', 'Romanian'],
  'Russia': ['English', 'Russian'],
  'Rwanda': ['English', 'French', 'Kinyarwanda', 'Swahili'],
  'Saint Kitts and Nevis': ['English'],
  'Saint Lucia': ['English'],
  'Saint Vincent and the Grenadines': ['English'],
  'Samoa': ['English', 'Samoan'],
  'San Marino': ['English', 'Italian'],
  'Sao Tome and Principe': ['English', 'Portuguese'],
  'Saudi Arabia': ['Arabic', 'English'],
  'Senegal': ['English', 'French'],
  'Serbia': ['English', 'Serbian'],
  'Seychelles': ['English', 'French', 'Seychellois Creole'],
  'Sierra Leone': ['English'],
  'Singapore': ['Chinese (Mandarin)', 'English', 'Malay', 'Tamil'],
  'Slovakia': ['English', 'Slovak'],
  'Slovenia': ['English', 'Slovene'],
  'Somalia': ['Arabic', 'English', 'Somali'],
  'South Africa': ['Afrikaans', 'English', 'Zulu'],
  'South Korea': ['English', 'Korean'],
  'South Sudan': ['English'],
  'Spain': ['English', 'Spanish'],
  'Sri Lanka': ['English', 'Sinhala', 'Tamil'],
  'Sudan': ['Arabic', 'English'],
  'Suriname': ['Dutch', 'English'],
  'Sweden': ['English', 'Swedish'],
  'Switzerland': ['English', 'French', 'German', 'Italian'],
  'Syria': ['Arabic', 'English'],
  'Taiwan': ['Chinese (Mandarin)', 'English'],
  'Tajikistan': ['English', 'Tajik'],
  'Tanzania': ['English', 'Swahili'],
  'Thailand': ['English', 'Thai'],
  'Timor-Leste': ['English', 'Portuguese', 'Tetum'],
  'Togo': ['English', 'French'],
  'Tonga': ['English', 'Tongan'],
  'Trinidad and Tobago': ['English'],
  'Tunisia': ['Arabic', 'English'],
  'Turkey': ['English', 'Turkish'],
  'Turkmenistan': ['English', 'Turkmen'],
  'Tuvalu': ['English', 'Tuvaluan'],
  'Uganda': ['English', 'Swahili'],
  'Ukraine': ['English', 'Ukrainian'],
  'United Arab Emirates': ['Arabic', 'English'],
  'United Kingdom': ['English'],
  'United States of America': ['Chinese (Mandarin)', 'English', 'Spanish'],
  'Uruguay': ['English', 'Spanish'],
  'Uzbekistan': ['English', 'Uzbek'],
  'Vanuatu': ['Bislama', 'English', 'French'],
  'Vatican City': ['English', 'Italian', 'Latin'],
  'Venezuela': ['English', 'Spanish'],
  'Vietnam': ['English', 'Vietnamese'],
  'Yemen': ['Arabic', 'English'],
  'Zambia': ['Bemba', 'English', 'Nyanja'],
  'Zimbabwe': ['English', 'Ndebele', 'Shona'],
};

export const ANDHRA_PRADESH_CONSTITUENCIES = [
  { id: 'jammalamadugu', name: 'Jammalamadugu', isReservedSC: true },
  { id: 'pulivendula', name: 'Pulivendula', isReservedSC: false },
  { id: 'badvel', name: 'Badvel', isReservedSC: true },
  { id: 'kamalapuram', name: 'Kamalapuram', isReservedSC: true },
  { id: 'mydukur', name: 'Mydukur', isReservedSC: true },
  { id: 'proddatur', name: 'Proddatur', isReservedSC: false },
  { id: 'allagadda', name: 'Allagadda', isReservedSC: false },
  { id: 'nandyal', name: 'Nandyal', isReservedSC: false },
  { id: 'panyam', name: 'Panyam', isReservedSC: false },
  { id: 'rayadurg', name: 'Rayadurg', isReservedSC: true },
  { id: 'uravakonda', name: 'Uravakonda', isReservedSC: false },
  { id: 'guntakal', name: 'Guntakal', isReservedSC: false },
  { id: 'singanamala', name: 'Singanamala', isReservedSC: true },
  { id: 'anantapur', name: 'Anantapur', isReservedSC: false },
  { id: 'kalyandurg', name: 'Kalyandurg', isReservedSC: true },
  { id: 'kadiri', name: 'Kadiri', isReservedSC: false },
  { id: 'kurnool', name: 'Kurnool', isReservedSC: false },
  { id: 'adoni', name: 'Adoni', isReservedSC: true },
  { id: 'yemmiganur', name: 'Yemmiganur', isReservedSC: false },
  { id: 'pattikonda', name: 'Pattikonda', isReservedSC: true },
  { id: 'nandikotkur', name: 'Nandikotkur', isReservedSC: true },
  { id: 'dharmavaram', name: 'Dharmavaram', isReservedSC: false },
  { id: 'penukonda', name: 'Penukonda', isReservedSC: false },
  { id: 'puttaparthi', name: 'Puttaparthi', isReservedSC: false },
  { id: 'hindupur', name: 'Hindupur', isReservedSC: false },
  { id: 'muddegama', name: 'Muddegama', isReservedSC: false },
  { id: 'tadepalligudem', name: 'Tadepalligudem', isReservedSC: false },
];