
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Megaphone, PlayCircle, RadioTower, Smartphone, Wand2, Film, CheckCircle, ArrowRight, Video, Clapperboard, MousePointerClick } from 'lucide-react';
import { CreateAdModal } from '../components/CreateAdModal';
import { CreateShortsAdModal } from '../components/CreateShortsAdModal';
import { CreateUnskippableAdModal } from '../components/CreateUnskippableAdModal';
import { AdCampaign, ShortsAdCampaign, UnskippableAdCampaign } from '../types';

// Simplified type for our model templates
interface AdModel {
    id: string;
    title: string;
    type: 'standard' | 'shorts' | 'veo' | 'bumper';
    description: string;
    category: string;
}

const USER_ADS_KEY = 'starlight_user_ads';

export const AdCreationHub: React.FC = () => {
    const navigate = useNavigate();
    const [activeTab, setActiveTab] = useState<'all' | 'video' | 'shorts' | 'motion'>('all');
    
    // State for modals
    const [showStandardModal, setShowStandardModal] = useState(false);
    const [showShortsModal, setShowShortsModal] = useState(false);
    const [showBumperModal, setShowBumperModal] = useState(false);

    // Mock "100 Models" - generating programmatically to save space but simulating variety
    const models: AdModel[] = [
        // Standard Video Models
        { id: 'm1', title: 'Product Launch Showcase', type: 'standard', description: 'High-impact 16:9 video ad for new product reveals.', category: 'Marketing' },
        { id: 'm2', title: 'Brand Awareness Story', type: 'standard', description: 'Narrative-driven ad to build brand connection.', category: 'Branding' },
        { id: 'm3', title: 'Tutorial / How-To', type: 'standard', description: 'Educational content that subtly promotes your service.', category: 'Education' },
        { id: 'm4', title: 'Customer Testimonial', type: 'standard', description: 'Social proof focused ad featuring user reviews.', category: 'Social' },
        { id: 'm5', title: 'Limited Time Offer', type: 'standard', description: 'Urgency-driven ad with countdown elements.', category: 'Sales' },
        
        // Shorts Models
        { id: 'm6', title: 'Viral Challenge', type: 'shorts', description: 'Vertical 9:16 format optimized for high engagement.', category: 'Social' },
        { id: 'm7', title: 'Behind the Scenes', type: 'shorts', description: 'Authentic, vertical look at your company culture.', category: 'Branding' },
        { id: 'm8', title: 'Quick Tip', type: 'shorts', description: 'Fast, value-packed vertical video for feed scrolling.', category: 'Education' },
        { id: 'm9', title: 'Influencer Collab', type: 'shorts', description: 'Vertical split-screen style for partnerships.', category: 'Marketing' },
        
        // Bumper Models (Unskippable)
        { id: 'm10', title: '6s Quick Impact', type: 'bumper', description: 'Unskippable bumper ad for maximum recall.', category: 'Branding' },
        { id: 'm11', title: '15s Mid-Roll Interruption', type: 'bumper', description: 'Non-skippable ad placed during long-form content.', category: 'Marketing' },
        
        // Motion / Veo Models
        { id: 'm12', title: 'AI Cinematic Reveal', type: 'veo', description: 'Generate stunning 4K visuals from text prompts with Veo.', category: 'AI Lab' },
        { id: 'm13', title: 'Motion Graphic Intro', type: 'veo', description: 'Dynamic text and shape animation generated by AI.', category: 'AI Lab' },
        { id: 'm14', title: 'Abstract Background Loop', type: 'veo', description: 'Perfect for music or ambiance, AI generated.', category: 'AI Lab' },
        { id: 'm15', title: 'Surreal Product Placement', type: 'veo', description: 'Place your product in AI-imagined worlds.', category: 'AI Lab' },
    ];

    const filteredModels = activeTab === 'all' 
        ? models 
        : activeTab === 'video' 
            ? models.filter(m => m.type === 'standard' || m.type === 'bumper')
            : activeTab === 'shorts'
                ? models.filter(m => m.type === 'shorts')
                : models.filter(m => m.type === 'veo');

    const handleModelClick = (model: AdModel) => {
        switch (model.type) {
            case 'standard':
                setShowStandardModal(true);
                break;
            case 'shorts':
                setShowShortsModal(true);
                break;
            case 'bumper':
                setShowBumperModal(true);
                break;
            case 'veo':
                navigate('/cinematic-ad-creator');
                break;
        }
    };

    const handleCreateSuccess = (newCampaign: AdCampaign | ShortsAdCampaign | UnskippableAdCampaign) => {
        // Save to local storage generic handler
        const userAdsJson = localStorage.getItem(USER_ADS_KEY);
        const allUserAds = userAdsJson ? JSON.parse(userAdsJson) : [];
        allUserAds.unshift(newCampaign);
        localStorage.setItem(USER_ADS_KEY, JSON.stringify(allUserAds));
        
        setShowStandardModal(false);
        setShowShortsModal(false);
        setShowBumperModal(false);
        
        // Navigate to management page
        if ('duration' in newCampaign) {
             navigate('/unskippable-ads');
        } else if ('impressions' in newCampaign && !('duration' in newCampaign)) {
             navigate('/shorts-ads');
        } else {
             navigate('/skippable-ads');
        }
    };

    return (
        <div className="w-full h-full bg-[var(--background-primary)] text-[var(--text-primary)] p-6 md:p-12 overflow-y-auto">
            {/* Modals */}
            {showStandardModal && <CreateAdModal onClose={() => setShowStandardModal(false)} onSuccess={handleCreateSuccess} />}
            {showShortsModal && <CreateShortsAdModal onClose={() => setShowShortsModal(false)} onSuccess={handleCreateSuccess} />}
            {showBumperModal && <CreateUnskippableAdModal onClose={() => setShowBumperModal(false)} onSuccess={handleCreateSuccess} />}

            <div className="max-w-7xl mx-auto">
                {/* Hero Section */}
                <div className="text-center mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
                    <div className="flex justify-center mb-6">
                        <div className="p-5 rounded-3xl bg-[hsl(var(--accent-color))]/10 shadow-lg shadow-[hsl(var(--accent-color))]/5">
                            <Megaphone className="w-16 h-16 text-[hsl(var(--accent-color))]" />
                        </div>
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-[hsl(var(--accent-color))] to-purple-600 tracking-tight">
                        Ad Creation Studio
                    </h1>
                    <p className="text-xl text-[var(--text-secondary)] max-w-2xl mx-auto leading-relaxed">
                        Choose from over 100+ AI-powered ad models. Create, edit, and launch campaigns across StarLight, Shorts, and Live.
                    </p>
                </div>

                {/* Tabs */}
                <div className="flex justify-center mb-10 overflow-x-auto no-scrollbar">
                    <div className="flex gap-2 p-1 bg-[var(--background-secondary)] rounded-xl border border-[var(--border-primary)]">
                        <button onClick={() => setActiveTab('all')} className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap ${activeTab === 'all' ? 'bg-[hsl(var(--accent-color))] text-white shadow-md' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--background-tertiary)]'}`}>
                            All Models
                        </button>
                        <button onClick={() => setActiveTab('video')} className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap flex items-center gap-2 ${activeTab === 'video' ? 'bg-[hsl(var(--accent-color))] text-white shadow-md' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--background-tertiary)]'}`}>
                            <PlayCircle className="w-4 h-4"/> Video Ads
                        </button>
                        <button onClick={() => setActiveTab('shorts')} className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap flex items-center gap-2 ${activeTab === 'shorts' ? 'bg-[hsl(var(--accent-color))] text-white shadow-md' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--background-tertiary)]'}`}>
                            <Smartphone className="w-4 h-4"/> Shorts Ads
                        </button>
                        <button onClick={() => setActiveTab('motion')} className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap flex items-center gap-2 ${activeTab === 'motion' ? 'bg-[hsl(var(--accent-color))] text-white shadow-md' : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--background-tertiary)]'}`}>
                            <Wand2 className="w-4 h-4"/> AI Motion (Veo)
                        </button>
                    </div>
                </div>

                {/* Models Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                    {filteredModels.map((model, index) => (
                        <div 
                            key={model.id}
                            onClick={() => handleModelClick(model)}
                            className="bg-[var(--background-secondary)] rounded-2xl border border-[var(--border-primary)] overflow-hidden group hover:border-[hsl(var(--accent-color))] transition-all cursor-pointer hover:shadow-xl hover:-translate-y-1 animate-in fade-in"
                            style={{ animationDelay: `${index * 50}ms` }}
                        >
                            {/* Visual Preview Placeholder */}
                            <div className={`relative bg-[var(--background-tertiary)] w-full ${model.type === 'shorts' ? 'aspect-[9/16]' : 'aspect-video'} overflow-hidden`}>
                                <img 
                                    src={`https://picsum.photos/seed/${model.title.replace(/\s/g,'')}/400/${model.type === 'shorts' ? '711' : '225'}`} 
                                    className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
                                    alt={model.title}
                                />
                                <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-colors"></div>
                                <div className="absolute top-2 right-2 flex flex-col items-end gap-1">
                                    <span className="px-2 py-1 bg-black/60 text-white text-[10px] font-bold uppercase rounded-md backdrop-blur-sm tracking-wider">
                                        {model.type === 'veo' ? 'AI GEN' : model.type.toUpperCase()}
                                    </span>
                                </div>
                                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                    <div className="p-3 bg-[hsl(var(--accent-color))] text-white rounded-full shadow-lg transform scale-90 group-hover:scale-100 transition-transform">
                                        {model.type === 'veo' ? <Wand2 className="w-6 h-6"/> : <MousePointerClick className="w-6 h-6"/>}
                                    </div>
                                </div>
                            </div>

                            {/* Content */}
                            <div className="p-5">
                                <div className="text-xs font-bold text-[hsl(var(--accent-color))] mb-1 uppercase tracking-wider">{model.category}</div>
                                <h3 className="font-bold text-lg mb-2 text-[var(--text-primary)] leading-tight">{model.title}</h3>
                                <p className="text-sm text-[var(--text-secondary)] line-clamp-2">{model.description}</p>
                                
                                <div className="mt-4 pt-4 border-t border-[var(--border-primary)] flex items-center justify-between text-sm font-semibold text-[hsl(var(--accent-color))]">
                                    <span>Use Model</span>
                                    <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
                
                {/* Fallback for "100 models" */}
                <div className="mt-12 text-center">
                    <p className="text-[var(--text-tertiary)] text-sm mb-4">Displaying {filteredModels.length} of 100+ available ad models.</p>
                    <button className="px-6 py-3 border border-[var(--border-primary)] rounded-full text-sm font-bold text-[var(--text-secondary)] hover:bg-[var(--background-secondary)] transition-colors">
                        Load More Models
                    </button>
                </div>
            </div>
        </div>
    );
};
