
import React from 'react';
import { Play, Twitter, Facebook, Instagram } from 'lucide-react';
import { Logo } from '../components/Logo';

const MOCK_FEATURED_VIDEOS = [
  {
    id: 'vid-01',
    title: 'Exploring the Alps: A 4K Drone Adventure',
    communityName: 'Nature Explorers',
    thumbnailUrl: 'https://picsum.photos/seed/alps-email/400/225',
  },
  {
    id: 'vid-02',
    title: 'How to Make the PERFECT Sourdough Bread',
    communityName: 'Home Chef',
    thumbnailUrl: 'https://picsum.photos/seed/sourdough-email/400/225',
  },
  {
    id: 'vid-03',
    title: 'Cyberpunk 2077 - The Ultimate Graphics Mod Showcase',
    communityName: 'Gaming Central',
    thumbnailUrl: 'https://picsum.photos/seed/cyberpunk-email/400/225',
  },
];


export const BrandedEmail: React.FC = () => {
  return (
    <div className="p-4 sm:p-8 bg-gray-100 dark:bg-slate-800 min-h-full font-sans antialiased">
      
      {/* Email Client UI */}
      <div className="max-w-4xl mx-auto bg-white dark:bg-slate-900 rounded-xl shadow-2xl border border-gray-200 dark:border-slate-700">
        <div className="p-4 border-b border-gray-200 dark:border-slate-700">
            <div className="flex items-center gap-3 text-sm">
                <span className="text-gray-500 dark:text-slate-400 font-medium">From:</span>
                <span className="font-semibold text-gray-800 dark:text-slate-200 flex items-center gap-2">
                    <Logo className="w-4 h-4 text-blue-600"/>
                    StarLight Team &lt;team@starlight.app&gt;
                </span>
            </div>
             <div className="flex items-center gap-3 text-sm mt-2">
                <span className="text-gray-500 dark:text-slate-400 font-medium">To:</span>
                <span className="font-semibold text-gray-800 dark:text-slate-200 flex items-center gap-2">
                    New Creator &lt;new.creator@example.com&gt;
                </span>
            </div>
             <div className="mt-4">
                <h1 className="text-xl font-bold text-gray-900 dark:text-slate-100">Welcome to StarLight! ✨</h1>
            </div>
        </div>
        
        {/* Email Body */}
        <div className="bg-[#f9fafb] dark:bg-[#020617] p-0 md:p-2 lg:p-4">
            <div className="max-w-3xl mx-auto bg-white dark:bg-slate-900" style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"' }}>
                {/* Header */}
                <header className="bg-gradient-to-br from-blue-700 to-indigo-900 text-white text-center p-12">
                    <div className="flex justify-center items-center gap-3 mb-4">
                        <Logo className="w-12 h-12 text-white"/>
                        <span className="text-4xl font-bold tracking-tighter">StarLight</span>
                    </div>
                    <h2 className="text-3xl font-bold mb-2">Welcome to the Future of Content!</h2>
                    <p className="text-lg text-indigo-200">We're thrilled to have you join our community of creators and viewers.</p>
                </header>

                {/* Main Content */}
                <main className="p-8 text-gray-700 dark:text-slate-300">
                    <p className="text-lg mb-6">Hi there,</p>
                    <p className="mb-6 leading-relaxed">
                        Your journey on StarLight has just begun! Our platform is powered by generative AI to create a dynamic and endless stream of content. Whether you're here to watch, create, or discover, you're part of a revolution in digital media.
                    </p>
                    
                    <div className="text-center my-8">
                        <a href="#/profile" className="inline-block bg-blue-600 text-white font-bold py-4 px-8 rounded-full text-lg hover:bg-blue-700 transition-colors shadow-lg">
                           Complete Your Profile
                        </a>
                    </div>

                    <h3 className="text-2xl font-bold text-gray-900 dark:text-slate-100 border-b-2 border-blue-500 pb-2 mb-6">Get Inspired</h3>
                    <p className="mb-6">
                        Check out what's trending on StarLight. All titles, descriptions, and even thumbnails can be generated by our AI assistant to help you get started.
                    </p>

                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                        {MOCK_FEATURED_VIDEOS.map(video => (
                            <a href={`#/watch/${video.id}`} key={video.id} className="block group border border-gray-200 dark:border-slate-700 rounded-lg overflow-hidden hover:shadow-xl hover:-translate-y-1 transition-all">
                                <div className="relative">
                                    <img src={video.thumbnailUrl} alt={video.title} className="w-full h-auto aspect-video object-cover"/>
                                    <div className="absolute inset-0 bg-black/30 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                        <Play className="w-10 h-10 text-white fill-current"/>
                                    </div>
                                </div>
                                <div className="p-4 bg-white dark:bg-slate-800">
                                    <h4 className="font-bold text-sm text-gray-900 dark:text-slate-100 group-hover:text-blue-600 transition-colors line-clamp-2">{video.title}</h4>
                                    <p className="text-xs text-gray-500 dark:text-slate-400 mt-1">{video.communityName}</p>
                                </div>
                            </a>
                        ))}
                    </div>
                </main>

                {/* Footer */}
                <footer className="text-center p-8 border-t border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-800/50">
                    <p className="text-sm text-gray-600 dark:text-slate-400 mb-4">
                        Follow us on social media for updates and inspiration!
                    </p>
                    <div className="flex justify-center gap-6 mb-6">
                        <a href="#" className="text-gray-500 hover:text-blue-600 transition-colors"><Twitter className="w-6 h-6"/></a>
                        <a href="#" className="text-gray-500 hover:text-blue-600 transition-colors"><Facebook className="w-6 h-6"/></a>
                        <a href="#" className="text-gray-500 hover:text-blue-600 transition-colors"><Instagram className="w-6 h-6"/></a>
                    </div>
                    <p className="text-xs text-gray-400 dark:text-slate-500">
                        © 2025 Admin (Geddada Vijaykumar). All Rights Reserved. <br/>
                        You received this email because you signed up on StarLight.
                    </p>
                     <a href="#" className="text-xs text-gray-400 dark:text-slate-500 hover:underline mt-2 inline-block">Unsubscribe</a>
                </footer>
            </div>
        </div>
      </div>
    </div>
  );
};
