import React from 'react';
import { Shield, Copyright as CopyrightIcon, AlertCircle, FileText } from 'lucide-react';

export const Copyright: React.FC = () => {
  return (
    <div className="w-full h-full bg-[var(--background-primary)] text-[var(--text-primary)] p-6 md:p-12 overflow-y-auto">
      <div className="max-w-4xl mx-auto">
        <header className="mb-12 text-center animate-in fade-in slide-in-from-bottom-4 duration-700">
             <div className="flex justify-center mb-6">
                <div className="p-5 rounded-3xl bg-blue-500/10 shadow-lg shadow-blue-500/5">
                   <CopyrightIcon className="w-16 h-16 text-blue-500" />
                </div>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold mb-4">Copyright Policy</h1>
            <p className="text-[var(--text-secondary)] text-lg">
                Starlight respects the intellectual property rights of others and expects its users to do the same.
            </p>
        </header>

        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-100">
            <section className="bg-[var(--background-secondary)] p-8 rounded-2xl border border-[var(--border-primary)]">
                <div className="flex items-start gap-4">
                    <div className="p-2 bg-blue-500/10 rounded-lg text-blue-500 mt-1">
                        <FileText className="w-5 h-5" />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold mb-3">Our Content Policy</h2>
                        <p className="text-[var(--text-secondary)] leading-relaxed mb-4">
                            All content generated by the Starlight AI engine, including video titles, descriptions, comments, and simulated user interactions, is created for demonstration purposes. The underlying technology and interface design are © 2025 Admin (Geddada Vijaykumar).
                        </p>
                        <p className="text-[var(--text-secondary)] leading-relaxed">
                            Users are responsible for the content they upload. By uploading content, you grant Starlight a license to display and distribute it on the platform for the purpose of this demonstration.
                        </p>
                    </div>
                </div>
            </section>

            <section className="bg-[var(--background-secondary)] p-8 rounded-2xl border border-[var(--border-primary)]">
                <div className="flex items-start gap-4">
                     <div className="p-2 bg-red-500/10 rounded-lg text-red-500 mt-1">
                        <AlertCircle className="w-5 h-5" />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold mb-3">Copyright Infringement & DMCA</h2>
                        <p className="text-[var(--text-secondary)] leading-relaxed mb-4">
                            If you believe that your work has been copied in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information in accordance with the Digital Millennium Copyright Act (DMCA):
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-[var(--text-secondary)] ml-2 text-sm">
                            <li>A physical or electronic signature of the copyright owner or a person authorized to act on their behalf.</li>
                            <li>Identification of the copyrighted work claimed to have been infringed.</li>
                            <li>Identification of the material that is claimed to be infringing and where it is located on the platform.</li>
                            <li>Your contact information, including address, telephone number, and email.</li>
                            <li>A statement by you that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
                            <li>A statement that the information in the notification is accurate, and, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</li>
                        </ul>
                    </div>
                </div>
            </section>

            <section className="bg-[var(--background-secondary)] p-8 rounded-2xl border border-[var(--border-primary)]">
                <div className="flex items-start gap-4">
                    <div className="p-2 bg-green-500/10 rounded-lg text-green-500 mt-1">
                        <Shield className="w-5 h-5" />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold mb-3">Fair Use & Transformative Works</h2>
                        <p className="text-[var(--text-secondary)] leading-relaxed">
                            Starlight supports the principles of Fair Use. We encourage creators to produce transformative works, such as commentary, criticism, news reporting, and educational content. However, re-uploading someone else's content without permission or significant modification is not permitted and may result in a copyright strike.
                        </p>
                    </div>
                </div>
            </section>

             <div className="text-center text-[var(--text-tertiary)] text-sm pt-4">
                <p>For legal inquiries, please contact Admin: Geddada Vijaykumar</p>
                <p>Email: <a href="mailto:legal@starlight.app" className="text-[hsl(var(--accent-color))] hover:underline">legal@starlight.app</a> | WhatsApp: <a href="https://wa.me/919440566494" target="_blank" rel="noopener noreferrer" className="text-[hsl(var(--accent-color))] hover:underline">(+91) 9440566494</a></p>
            </div>
        </div>
      </div>
    </div>
  );
};