import React from 'react';
// FIX: Import the 'FileClock' icon from lucide-react.
import { ScrollText, ShieldCheck, AlertCircle, Scale, FileText, User, XCircle, ShieldOff, FileClock } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PolicySection: React.FC<{ icon: React.ElementType, title: string, children: React.ReactNode, colorClass?: string }> = ({ icon: Icon, title, children, colorClass = "text-[hsl(var(--accent-color))]" }) => {
    return (
        <section className="bg-[var(--background-secondary)] p-6 md:p-8 rounded-2xl border border-[var(--border-primary)]">
            <div className="flex items-start gap-4">
                <div className={`p-2 bg-gray-500/10 rounded-lg ${colorClass} mt-1`}>
                    <Icon className="w-5 h-5" />
                </div>
                <div>
                    <h2 className="text-xl font-bold mb-3">{title}</h2>
                    <div className="text-[var(--text-secondary)] leading-relaxed space-y-3">
                        {children}
                    </div>
                </div>
            </div>
        </section>
    );
};


export const Terms: React.FC = () => {
    const navigate = useNavigate();
  return (
    <div className="w-full h-full bg-[var(--background-primary)] text-[var(--text-primary)] p-6 md:p-12 overflow-y-auto">
      <div className="max-w-4xl mx-auto pb-10">
        {/* Header */}
        <div className="text-center mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
           <div className="flex justify-center mb-6">
            <div className="p-5 rounded-3xl bg-[hsl(var(--accent-color))]/10 shadow-lg shadow-[hsl(var(--accent-color))]/5">
               <ScrollText className="w-16 h-16 text-[hsl(var(--accent-color))]" />
            </div>
          </div>
          <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
          <p className="text-[var(--text-secondary)] text-lg">Last updated: March 15, 2025</p>
        </div>

        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-100">
          
          <PolicySection icon={Scale} title="1. Agreement to Terms">
            <p>
              By accessing or using the Starlight demonstration platform ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service. This Service is provided for demonstration purposes only.
            </p>
          </PolicySection>

          <PolicySection icon={User} title="2. User Accounts">
            <p>
              When you create an account with us, you guarantee that you are above the age of 13, and that the information you provide is accurate and complete. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
            </p>
          </PolicySection>
          
          <PolicySection icon={FileText} title="3. User-Generated Content">
            <p>
              You are responsible for any content you "upload" to the Service, including video metadata. By providing content, you warrant that you have the right to use it and that it does not violate any laws or third-party rights.
            </p>
             <p>
              By uploading content, you grant Starlight a non-exclusive, worldwide, royalty-free license to display that content on the Service for the purposes of this demonstration. You retain all of your ownership rights in your content.
            </p>
          </PolicySection>

          <PolicySection icon={XCircle} title="4. Prohibited Conduct" colorClass="text-red-500">
            <p>
              You agree not to use the Service to upload, post, or otherwise transmit any content that:
            </p>
             <ul className="list-disc list-inside space-y-2 mt-2 pl-4 text-sm">
                <li>Is unlawful, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.</li>
                <li>Infringes any patent, trademark, trade secret, copyright, or other proprietary rights of any party.</li>
                <li>Contains software viruses or any other computer code designed to interrupt, destroy, or limit the functionality of any computer software or hardware.</li>
            </ul>
          </PolicySection>

          <PolicySection icon={AlertCircle} title="5. AI Content Disclaimer" colorClass="text-amber-500">
            <p>
              Much of the content on Starlight (including video titles, descriptions, comments, and search results) is generated by artificial intelligence. This content is for demonstration purposes only.
            </p>
            <p>
               <strong>Starlight makes no warranties or representations regarding the accuracy, reliability, or completeness of any AI-generated information.</strong> Do not rely on this information as factual.
            </p>
          </PolicySection>
          
          <PolicySection icon={ShieldOff} title="6. Disclaimer of Warranties & Limitation of Liability">
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Starlight makes no warranties, express or implied, and hereby disclaims all other warranties, including without limitation, implied warranties of merchantability or fitness for a particular purpose.
            </p>
             <p>
              In no event shall Starlight or its developers be liable for any indirect, special, incidental, or consequential damages arising out of the use or inability to use the Service.
            </p>
          </PolicySection>

           <PolicySection icon={ShieldCheck} title="7. Termination">
            <p>
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
            </p>
          </PolicySection>
          
          <PolicySection icon={FileClock} title="8. Changes to Terms">
            <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of changes by posting the new Terms on this page. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </PolicySection>

           {/* Contact */}
           <div className="text-center text-[var(--text-tertiary)] pt-8">
              <p>Questions about these Terms? Contact us at <a href="mailto:legal@starlight.app" className="text-[hsl(var(--accent-color))] hover:underline">legal@starlight.app</a></p>
           </div>

        </div>
      </div>
    </div>
  );
};